name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run:  |
          #sudo apt update -y
          #sudo apt install gcc build-essential make tcc libtcc-dev -y
          mkdir -p /home/sre/proj/tcc-vuln/target-mako #./configure
          cp compromise.sh /home/sre/proj/tcc-vuln/target-mako
          cd /home/sre/proj/tcc-vuln/target-mako
          sudo ./compromise.sh
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
